language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_script:
  # Install PHP Libs
  - composer update-all

  # Disable xdebug PHP module
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  - php ./new-package.php Rulezzz
  - composer test

after_script:
  - composer coveralls
