language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_script:

  # Composer
  - composer self-update
  - composer update

  # Update env
  - phpenv rehash

script:
  # PHPUnit tests OR global testing
  - composer test

after_script:
  # Send to coveralls
  - php vendor/bin/coveralls --verbose
