language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_script:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  - echo -e "\e[0;33mTest \e[0;30;46m Label \e[0m"
  - echo -e "\e[0;33mTest \e[0;30;46m Label \e[0m"
  - echo -e "\033[0;33mTest \033[0;30;46m Label \033[0m"
  - echo -e "\e[0;33mTest Label\e[0m"
  - echo -e "\033[0;30;46m Test Label \e[0m"
  - exit

  - make new-project NAME=Rulezzz
  - make test-all

after_script:
  - make coveralls
