language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

env:
  - PHP_TEST_VERSION=5.6

before_script:
  # Composer
  - composer self-update
  - composer update
  - composer validate

  # Install reporting tools
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        composer require
          satooshi/php-coveralls
          squizlabs/php_codesniffer
          sebastian/phpcpd
          phploc/phploc
          phpmd/phpmd
        ;
    fi;'

  # Update env
  - phpenv rehash

script:
  # PHPUnit tests
  - php vendor/bin/phpunit

  # Check PHP Code Standarts
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        git clone --branch=master https://github.com/JBZoo/Misc.git build/misc;
        php vendor/bin/phpcs ./src --standard=build/misc/phpcs/JBZoo/ruleset.xml --report=full;
        php vendor/bin/phpmd ./src text ./build/misc/phpmd/jbzoo.xml --verbose;
        php vendor/bin/phpcpd ./src --no-interaction --verbose;
    fi;'

after_script:
  # Get statistics
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        php vendor/bin/coveralls --verbose;
        php vendor/bin/phploc ./src --no-interaction --verbose;
    fi;'

notifications:
  slack: jbzoo:RPyzxVQZPuPhgvm1Q6fDvK3C
