language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_script:
  - export PHP_TEST_VERSION=5.6

  # Composer
  - composer self-update

  # Install all testing and dev tools
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        composer update;
    else
        composer update --no-dev;
    fi;'

  # Update env
  - phpenv rehash

script:
  # PHPUnit tests OR global testing
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        composer test;
    else
        composer phpunit;
    fi;'

after_script:
  # Send to coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "$PHP_TEST_VERSION" ]; then
        php vendor/bin/coveralls --verbose;
    fi;'
